name: Build

on:
  push:
    branches: [cibuildwheel]
  #pull_request:
  #  branches: [main]

  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD_VERBOSITY: 1
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value