name: Build

on:
  push:
    branches: [cibuildwheel]
  #pull_request:
  #  branches: [main]

  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}   
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ENVIRONMENT_MACOS: CC=gcc-11 CXX=g++-11 FC=gfortran-11
          CIBW_ARCHS: auto64
          CIBW_SKIP: skip = pp* *-musllinux*

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl          