name: Test Fortran

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fortran-lang/setup-fpm@v4
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fpm-version: 'latest'
      - uses: msys2/setup-msys2@v2
        if: contains(matrix.os, 'windows')
        with:
          msystem: MINGW64
          install: >-
            git
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-fpm
      - name: Run tests with fpm for Windows
        if: contains(matrix.os, 'windows')          
        shell: msys2 {0}
        run: fpm test
      - name: Run tests with fpm for Unix
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: fpm test --compiler gfortran-10
