name: Test Fortran

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fortran-lang/setup-fpm@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests with fpm
        run: fpm test --compiler gfortran-10
