name: Test Fortran

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fortran-lang/setup-fpm@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      # Runs a single command using the runners shell
      - name: Run tests with fpm
        env:
          FC: gfortran-11
        run: fpm test --compiler gfortran-11
