name: Test Fortran

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fortran-lang/setup-fpm@v2
      
      # Runs a single command using the runners shell
      - name: Run tests with fpm
        run: fpm test
